- name: install packages in east servers
  hosts: east
  become: yes
  vars_files:
    - vars.yml

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install developer tools
    apt:
      name: "{{ packages }}"
      state: present
